# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 00:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20170404_0008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materia',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='favorite',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='title',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='nombres',
            field=models.CharField(default=b'No nombres', max_length=50),
        ),
    ]
